config/routes.rb
Rails.application.routes.draw do
  # Gem Adminsitrate creates the routes to access users and expenses models in an admin site
  namespace :admin do
    resources :users
    resources :expenses

    root to: "users#index"
  end

  # creates routes for expenses model
  resources :expenses

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expense.rb
class Expense < ApplicationRecord
  # Validates the expense creation in order to correctly create a new expense.
  validates :total, presence: true
  validates :location, presence: true
  validates :user, presence: true

  # belongs_to is a property that makes the expense model, literally, belong to a user.
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # attr_accessor :email, :password, :password_confirmation, :remember_me, :name
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # has_many is an attribute that allows the userto have many expense models.
  has_many :expenses

end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# Gem controller, demands http authentication in order to allow the admin or client access.
module Admin
  class ApplicationController < Administrate::ApplicationController
    http_basic_authenticate_with name: 'alvaro', password: 'password'
  end
end

app/controllers/admin/expenses_controller.rb
module Admin
  class ExpensesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Expense.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Expense.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
# Controls application, demands user login.
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

   protected

   def configure_permitted_parameters
         devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
         devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
         devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/expenses_controller.rb
# Controller that allows the user to handle expense reports.
class ExpensesController < ApplicationController
  before_action :set_expense, only: [:show, :edit, :update, :destroy]

  # index displays all current user expense reports, or will go to homepage if there is no user.
  def index
    @expenses = Expense.all
    unless current_user
      redirect_to root_url
    end
  end

  # show displays specific expense report
  def show
  end

  # Template that allows the user to upload a new expense report.
  def new
    @expense = Expense.new
  end

  # Template that allows the user to correct or edit an existing expense.
  def edit
  end

  # Upon successful report, will upload a new expense.
  # Otherwise, will show error message.
  def create
    @expense = Expense.new(expense_params)

    respond_to do |format|
      if @expense.save
        format.html { redirect_to @expense, notice: 'Expense was successfully created.' }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # Action that requests an update to the database
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to @expense, notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # Upon user selection, will act and delete the selected expense.
  def destroy
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to expenses_url, notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Selects the created expense by id, in order to edit or destroy
    def set_expense
      @expense = Expense.find(params[:id])
    end

    # Required data to create an expense.
    def expense_params
      params.require(:expense).permit(:location, :description, :total, :date).
      merge(user: current_user)
    end
end

app/controllers/home_controller.rb
# Controller purpose: Allows homepage to exist.
class HomeController < ApplicationController
  def index
  end
end

app/controllers/user_controller.rb
# Controller to create new user
class UserController < ApplicationController
  # Requires user_params detailed below.
  def create
    @user = User.new(user_params)

    # Upon successful user registration, will proceed to root_url.
    # Else, it will refresh the page and flash an error notice.
    if @user.save
      sign_in(@user)
      redirect_to root_url
    else
      flash.now[:notice] = "Por favor llena el registro correctamente."
      render :new
    end
  end

  private

  # Required parameters: Full name, email, and password respectively.
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/application/_collection.html.erb
<%#
# Collection

This partial is used on the `index` and `show` pages
to display a collection of resources in an HTML table.

## Local variables:

- `collection_presenter`:
  An instance of [Administrate::Page::Collection][1].
  The table presenter uses `ResourceDashboard::COLLECTION_ATTRIBUTES` to determine
  the columns displayed in the table
- `resources`:
  An ActiveModel::Relation collection of resources to be displayed in the table.
  By default, the number of resources is limited by pagination
  or by a hard limit to prevent excessive page load times

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>

<table class="collection-data" aria-labelledby="page-title">
  <thead>
    <tr>
      <% collection_presenter.attribute_types.each do |attr_name, attr_type| %>
        <th class="cell-label
        cell-label--<%= attr_type.html_class %>
        cell-label--<%= collection_presenter.ordered_html_class(attr_name) %>
        " scope="col">
        <%= link_to(sanitized_order_params.merge(
          collection_presenter.order_params_for(attr_name)
        )) do %>
        <%= t(
          "helpers.label.#{resource_name}.#{attr_name}",
          default: attr_name.to_s,
        ).titleize %>

            <% if collection_presenter.ordered_by?(attr_name) %>
              <span class="cell-label__sort-indicator cell-label__sort-indicator--<%= collection_presenter.ordered_html_class(attr_name) %>">
                <%= svg_tag(
                  "administrate/sort_arrow.svg",
                  "sort_arrow",
                  width: "13",
                  height: "13"
                ) %>
              </span>
            <% end %>
          <% end %>
        </th>
      <% end %>
      <th colspan="2" scope="col"></th>
    </tr>
  </thead>

  <tbody>
    <% resources.each do |resource| %>
      <tr class="table__row"
          role="link"
          tabindex="0"
          data-url="<%= polymorphic_path([namespace, resource]) -%>"
          >
        <% collection_presenter.attributes_for(resource).each do |attribute| %>
          <td class="cell-data cell-data--<%= attribute.html_class %>">
            <%= render_field attribute %>
          </td>
        <% end %>

        <td><%= link_to(
          t("administrate.actions.edit"),
          [:edit, namespace, resource],
          class: "action-edit",
        ) %></td>

        <td><%= link_to(
          t("administrate.actions.destroy"),
          [namespace, resource],
          class: "table__action--destroy",
          method: :delete,
          data: { confirm: t("administrate.actions.confirm") }
        ) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/application/index.html.erb
<%#
# Index

This view is the template for the index page.
It is responsible for rendering the search bar, header and pagination.
It renders the `_table` partial to display details about the resources.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Collection][1].
  Contains helper methods to help display a table,
  and knows which attributes should be displayed in the resource's table.
- `resources`:
  An instance of `ActiveRecord::Relation` containing the resources
  that match the user's search criteria.
  By default, these resources are passed to the table partial to be displayed.
- `search_term`:
  A string containing the term the user has searched for, if any.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>

<% content_for(:title) do %>
  <%= display_resource_name(page.resource_name) %>
<% end %>

<% content_for(:search) do %>
  <%= render "search", search_term: search_term %>
<% end %>

<header class="header">
  <h1 class="header__heading" id="page-title"><%= content_for(:title) %></h1>
  <!-- <div class="header__actions">
    <%#= link_to(
      "New #{page.resource_name.titleize.downcase}",
      [:new, namespace, page.resource_name],
      class: "button",
    ) %>
  </div> -->
</header>

<%= render "collection", collection_presenter: page, resources: resources %>

<%= paginate resources %>

app/views/admin/expenses/_collection.html.erb
<%#
# Collection

This partial is used on the `index` and `show` pages
to display a collection of resources in an HTML table.

## Local variables:

- `collection_presenter`:
  An instance of [Administrate::Page::Collection][1].
  The table presenter uses `ResourceDashboard::COLLECTION_ATTRIBUTES` to determine
  the columns displayed in the table
- `resources`:
  An ActiveModel::Relation collection of resources to be displayed in the table.
  By default, the number of resources is limited by pagination
  or by a hard limit to prevent excessive page load times

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>

<table class="collection-data" aria-labelledby="page-title">
  <thead>
    <tr>
      <% collection_presenter.attribute_types.each do |attr_name, attr_type| %>
        <th class="cell-label
        cell-label--<%= attr_type.html_class %>
        cell-label--<%= collection_presenter.ordered_html_class(attr_name) %>
        " scope="col">
        <%= link_to(sanitized_order_params.merge(
          collection_presenter.order_params_for(attr_name)
        )) do %>
        <%= t(
          "helpers.label.#{resource_name}.#{attr_name}",
          default: attr_name.to_s,
        ).titleize %>

            <% if collection_presenter.ordered_by?(attr_name) %>
              <span class="cell-label__sort-indicator cell-label__sort-indicator--<%= collection_presenter.ordered_html_class(attr_name) %>">
                <%= svg_tag(
                  "administrate/sort_arrow.svg",
                  "sort_arrow",
                  width: "13",
                  height: "13"
                ) %>
              </span>
            <% end %>
          <% end %>
        </th>
      <% end %>
      <th colspan="2" scope="col"></th>
    </tr>
  </thead>

  <tbody>
    <% resources.each do |resource| %>
      <tr class="table__row"
          role="link"
          tabindex="0"
          data-url="<%= polymorphic_path([namespace, resource]) -%>"
          >
        <% collection_presenter.attributes_for(resource).each do |attribute| %>
          <td class="cell-data cell-data--<%= attribute.html_class %>">
            <%= render_field attribute %>
          </td>
        <% end %>

        <td><%= link_to(
          t("administrate.actions.edit"),
          [:edit, namespace, resource],
          class: "action-edit",
        ) %></td>

        <td><%= link_to(
          t("administrate.actions.destroy"),
          [namespace, resource],
          class: "table__action--destroy",
          method: :delete,
          data: { confirm: t("administrate.actions.confirm") }
        ) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/expenses/index.html.erb
<%#
# Index

This view is the template for the index page.
It is responsible for rendering the search bar, header and pagination.
It renders the `_table` partial to display details about the resources.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Collection][1].
  Contains helper methods to help display a table,
  and knows which attributes should be displayed in the resource's table.
- `resources`:
  An instance of `ActiveRecord::Relation` containing the resources
  that match the user's search criteria.
  By default, these resources are passed to the table partial to be displayed.
- `search_term`:
  A string containing the term the user has searched for, if any.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>

<% content_for(:title) do %>
  <%= display_resource_name(page.resource_name) %>
<% end %>

<% content_for(:search) do %>
  <%= render "search", search_term: search_term %>
<% end %>

<header class="header">
  <h1 class="header__heading" id="page-title"><%= content_for(:title) %></h1>
  <!-- <div class="header__actions">
    <%#= link_to(
      "New #{page.resource_name.titleize.downcase}",
      [:new, namespace, page.resource_name],
      class: "button",
    ) %>
  </div> -->
</header>

<%= render "collection", collection_presenter: page, resources: resources %>

<%= paginate resources %>

app/views/expenses/_form.html.erb
<%= form_for(expense) do |f| %>
<!-- If an error or exception is found, will appear in its corresponding field -->
  <% if expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
      <% expense.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :total %>
    <%= f.text_field :total %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.date_select :date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing Expense</h1>

<%= render 'form', expense: @expense %>

<%= link_to 'Show', @expense %> |
<%= link_to 'Back', expenses_path %>

app/views/expenses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Expenses</h1>

<table>
  <thead>
    <tr>
      <th>Location</th>
      <th>Description</th>
      <th>Total</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <!-- Runs a loop through the logged user's existing expenses. -->
    <% current_user.expenses.each do |expense| %>
      <tr>
        <td><%= expense.location %></td>
        <td><%= expense.description %></td>
        <td><%= expense.total %></td>
        <td><%= expense.date %></td>
        <td><%= link_to 'Show', expense %></td>
        <td><%= link_to 'Edit', edit_expense_path(expense) %></td>
        <td><%= link_to 'Destroy', expense, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Expense', new_expense_path %>

app/views/expenses/new.html.erb
<h1>New Expense</h1>

<%= render 'form', expense: @expense %>

<%= link_to 'Back', expenses_path %>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<!-- @expense = set_expense by id -->

<p>
  <strong>Location:</strong>
  <%= @expense.location %>
</p>

<p>
  <strong>Description:</strong>
  <%= @expense.description %>
</p>

<p>
  <strong>Total:</strong>
  <%= @expense.total %>
</p>

<p>
  <strong>Date:</strong>
  <%= @expense.date %>
</p>

<%= link_to 'Edit', edit_expense_path(@expense) %> |
<%= link_to 'Back', expenses_path %>

app/views/home/index.html.erb
<h1>Welcome to the Finance Management App.</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceManagement</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Finance Management</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><a href="/admin">Admin</a></li>

          </ul>

          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><a href="/expenses">Expenses</a></li>
              <li><a href="/users/edit" ><%= current_user.name %></a></li>
              <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to 'Sign up', new_user_registration_path %></li>
              <li><%= link_to 'Login', new_user_session_path %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <div>



      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <%= yield %>
  </body>
</html>